cp /Users/sarnobat/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar .
cp /Users/sarnobat/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar .
cp /Users/sarnobat/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar .
cp /Users/sarnobat/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar .
cp /Users/sarnobat/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar .
cp /Users/sarnobat/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar .
cp /Users/sarnobat/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar .
cp /Users/sarnobat/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0/javax.ws.rs-api-2.0.jar .
cp /Users/sarnobat/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar .
cp /Users/sarnobat/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar .
cp /Users/sarnobat/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/plugins/maven-compiler-plugin/3.0/maven-compiler-plugin-3.0.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/2.4.3/maven-resources-plugin-2.4.3.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/shared/maven-filtering/1.0-beta-4/maven-filtering-1.0-beta-4.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/shared/maven-shared-incremental/1.0/maven-shared-incremental-1.0.jar .
cp /Users/sarnobat/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.jar .
cp /Users/sarnobat/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.0/plexus-compiler-api-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/2.0/plexus-compiler-javac-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-compiler-manager/2.0/plexus-compiler-manager-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar .
cp /Users/sarnobat/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.1.88/asm-all-repackaged-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/external/cglib/2.1.88/cglib-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/external/javax.inject/2.1.88/javax.inject-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/hk2-api/2.1.88/hk2-api-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/hk2-locator/2.1.88/hk2-locator-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/hk2-utils/2.1.88/hk2-utils-2.1.88.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/jersey/containers/jersey-container-jdk-http/2.0/jersey-container-jdk-http-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/jersey/core/jersey-client/2.0/jersey-client-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/jersey/core/jersey-common/2.0/jersey-common-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/glassfish/jersey/core/jersey-server/2.0/jersey-server-2.0.jar .
cp /Users/sarnobat/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar .
